### ISSUE TITLE
nssm install doesn't work with 4 socket CPU server

### ISSUE THREAD

**Issue by foi** [kirillkovalenko/nssm#8]
Hi! 

OS: Windows Server 2012 R2
When i type nssm install servicename
nssm loads 2 cores (from 64 - 4 CPU - 1 CPU 8 Cores/16 Threads)  on 100% and hangs. In application event journal doesnt include anything associated with nssm.

P.S. Thanks for awesome utility.

**Comment by kirillkovalenko** [comment]
I'm not an owner of this code, Iain Patterson is.
This repo is just a mirror of Iain's original repo at https://nssm.cc

**Comment by ghost** [comment]
Is there a possibility when stopping an installed service to give the control to nssm to run a java command for stopping application gracefully instead of nssm terminating it?

For instance I have a java class that needs to have STOP G parameter passed in order to stop the running application gracefully:
Whenever user stops the service (net stop "service_name") nssm should execute something like a hook, but for stopping the application gracefully:
java -jar application.jar stop G

Thanks

**Comment by foi** [comment]
bug was fixed in nssm 2.24-103-gdee49fc (2017-05-16)
